---
- name: Converge
  hosts: all

  roles:
    - role: tychobrouwer.git
      git_name: Test Test
      git_email: test@test.com

    - role: tychobrouwer.nordvpn
      nordvpn_username: test
      nordvpn_password: test
      nordvpn_server: us10036.nordvpn.com.udp1194
      nordvpn_no_redirect_gateway: true
      nordvpn_is_test: true

    - role: ansible-qbittorrent-nox
      qbittorrent_nox_torrent_path: /share/video-share/Torrents
